name: 'club'
version: '1.0.0'

profile: 'club'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         
  - "target"
  - "dbt_packages"


# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  club:
    marts:
      daily_hour_distribution:
        materialized: table  # Maybe 'incremental' ???
      +materialized: table
    static:
      +materialized: table 

seeds:
  my_project_name:
    stat_weekdays:
      file: seeds/stat_weekdays.csv   # Path to the CSV file
      header: true
      delimiter: ','                  # Default delimiter
      quote: '"'                       # Default quote
      materialized: table              # Define whether it's materialized as a table or view
